### ISSUE TITLE
Publish documentation from readthedocs

### ISSUE THREAD

**Issue by ryanmwhitephd** [ryanmwhitephd/artemis#35]
@DominicParent 

Please publish the documentation to readthedocs based on:
https://github.com/artemis-analytics/artemis/commit/9aa841a2583b3916f508a9b3565fb7e9f4a9c4b2

The current documentation includes:
* Updated style
* Updated docstrings which use numpy docstring style
* API reference
* Description of Algorithms and tools
* Development documentation for cython, C++, Arrow and python

**Comment by DominicParent** [comment]
Looks like the sphinx build of readthedocs uses sphinx 1.8.5 by default, which crashes due to errors. We've been using the more recent version of sphinx (2.4.3). I'll set the configuration files required to have sphinx build the docs properly.

I'll be creating branch bug-rtdconfig-35 to solve this.

**Comment by DominicParent** [comment]
Branch was created to fix the issue. I've successfully built a version of the documentation and pushed it to readthedocs. The current solution revolves around having a docs/requirements.txt file to define the use of sphinx>2.0.

I created pull request #37 and requested review by @ryanmwhitephd.

You can view the documentation here: https://pyartemis.readthedocs.io/en/bug-rtdconfig-35/

**Comment by DominicParent** [comment]
The pull request #37 was merged. The documentation is built (as of today) from the master branch.
